config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'stations#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :bikes
  resources :trips
  resources :stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stations
      patch  '/catch_bike' => 'bikes#catch'
      patch  '/give_back_bike' => 'bikes#give_back'
      post   '/sign_in'  => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
  end
end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: %i[show edit update destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user_id: current_user.id)
  end

  # GET /trips/1
  # GET /trips/1.json
  def show; end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit; end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(:origin, :destination, :bike_id, :started_at, :finished_at, :traveled_distance)
  end
end

app/helpers/trips_helper.rb
# frozen_string_literal: true

module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origin %>
    <%= form.number_field :origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.number_field :destination %>
  </div>

  <div class="field">
    <%= form.label :bike_id %>
    <%= form.number_field :bike_id %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.datetime_select :finished_at %>
  </div>

  <div class="field">
    <%= form.label :traveled_distance %>
    <%= form.number_field :traveled_distance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Origin</th>
      <th scope="col">Destination</th>
      <th scope="col">Bike</th>
      <th scope="col">Started at</th>
      <th scope="col">Finished at</th>
      <th scope="col">Traveled distance</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.origin %></td>
        <td><%= trip.destination %></td>
        <td><%= trip.bike_id %></td>
        <td><%= trip.started_at %></td>
        <td><%= trip.finished_at %></td>
        <td><%= trip.traveled_distance %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @trip.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<p>
  <strong>Bike:</strong>
  <%= @trip.bike_id %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @trip.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @trip.finished_at %>
</p>

<p>
  <strong>Traveled distance:</strong>
  <%= @trip.traveled_distance %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>