config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'stations#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :bikes
  resources :trips
  resources :stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stations
      patch  '/catch_bike' => 'bikes#catch'
      patch  '/give_back_bike' => 'bikes#give_back'
      post   '/sign_in'  => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
  end
end

app/models/station.rb
# frozen_string_literal: true

class Station < ApplicationRecord
  has_many :vacancies

  def vacancies_free_count
    vacancies.where(free: true).count
  end

  def vacancies_occupied_count
    vacancies.where(free: false).count
  end

  def bikes_on_station
    vacancies.map(&:bike)
  end
end

app/controllers/api/v1/stations_controller.rb
# frozen_string_literal: true

class Api::V1::StationsController < ApplicationController
  before_action :set_station, only: %i[show edit update destroy]
  before_action :load_user

  def index
    @stations = Station.all
    render json: @stations, methods: %i[vacancies_free_count vacancies_occupied_count bikes_on_station]
  end

  def show; end

  private

  def set_station
    @station = Station.find(params[:id])
  end

  def load_user
    if params[:auth_token].present?
      @current_user = User.where(token: params[:auth_token]).try(:first)
      render json: { status: 'Unauthorized', code: 401, message: 'Token invalid!' } unless @current_user
    else
      render json: { status: 'Unauthorized', code: 401, message: 'Token invalid!' }
    end
  end

end

app/controllers/stations_controller.rb
# frozen_string_literal: true

class StationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_station, only: %i[show edit update destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show; end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit; end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        @station.vacancies_bike.times do
          Vacancy.create(station_id: @station.id)
        end
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def station_params
    params.require(:station).permit(:name, :vacancies_bike)
  end
end

app/helpers/api/v1/stations_helper.rb
# frozen_string_literal: true

module Api::V1::StationsHelper
end

app/helpers/stations_helper.rb
# frozen_string_literal: true

module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
        <% station.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
 
  <div class="field">
    <%= form.label :vacancies %>
    <%= form.number_field :vacancies_bike %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Vacancies</th>
      <th scope="col">Vacancies Free</th>
      <th scope="col">Vacancies Occupied</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.vacancies_bike %></td>
        <td><%= station.vacancies_free_count %></td>
        <td><%= station.vacancies_occupied_count %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>


<p>
  <strong>Bikes:</strong>
  <%= @station.vacancies.each(&:bike) %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>