config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'stations#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :bikes
  resources :trips
  resources :stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stations
      patch  '/catch_bike' => 'bikes#catch'
      patch  '/give_back_bike' => 'bikes#give_back'
      post   '/sign_in'  => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
  end
end

app/models/bike.rb
# frozen_string_literal: true

class Bike < ApplicationRecord
  belongs_to :vacancy

  def self.create_trip_and_empty_vacancy(bike, user)
    Trip.create origin: bike.vacancy.station_id, bike_id: bike.id, started_at: Time.now , user_id: user.id
    bike.vacancy.update_attribute :free, true
    update_bike(bike, 0)
  end

  def self.update_trip_and_occupy_vacancy(trip, params, bike)
    vacancy = Vacancy.where(station_id: params[:destination], free: true).first
    raise 'There is no vacancy at this station. Please apply for another one that has vacancies.' unless vacancy

    vacancy.update_attribute :free, false
    update_bike(bike, vacancy.id, params[:with_problem])
    trip.update destination: params[:destination], finished_at: Time.now, traveled_distance: params[:distance]
    send_bike_broken(bike)
  end

  def self.update_bike(bike, vacancy_id, problem = false)
    bike.update vacancy_id: vacancy_id, with_problem: problem
  end

  private

  def self.send_bike_broken(bike)
    BikeMailer.with(id: bike.id).problem?.deliver_now if bike[:with_problem]
  end
end

app/controllers/api/v1/bikes_controller.rb
# frozen_string_literal: true

class Api::V1::BikesController < ApplicationController
  before_action :set_bike, only: %i[show catch give_back]
  before_action :get_trip, only: %i[give_back catch]
  before_action :load_user
  skip_before_action :verify_authenticity_token

  def index
    @bikes = Bike.all
    render json: @bikes
  end

  def show; end

  def catch
    if !@bike.with_problem
      if @trip
        @message = 'This bike is in a trip. Choose another.'
      else
        Bike.create_trip_and_empty_vacancy @bike, @current_user
        @message = 'Bike catch! Congrats!'
      end
      render json: { status: 'ok', code: 200, message: @message }
    else
      render json: { status: 'error', code: 3000, message: 'I`m sorry, but the bike has a problem. You can`t catch her.' }
    end
  end

  def give_back
    if @trip
      if @trip.origin != params[:destination].to_i
        Bike.update_trip_and_occupy_vacancy @trip, params, @bike
        @message = 'Ok. Thanks for use #BikeLikeYou. See ya later'
      else
        @message = 'Station destination is the same as station origin. Please return the bike to another station.'
      end
      render json: { status: 'ok', code: 200, message: @message }
    else
      render json: { status: 'error', code: 3000, message: 'I`m sorry, but the bike isn`t in a trip. You can`t give it back.' }
    end
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def get_trip
    @trip = Trip.find_by(bike_id: @bike.id, destination: nil)
  end

  def bike_params
    params.require(:bike).permit(:vacancy_id, :with_problem)
  end

  def load_user
    if params[:auth_token].present?
      @current_user = User.where(token: params[:auth_token]).try(:first)
      render json: { status: 'Unauthorized', code: 401, message: 'Unauthorized. Token invalid!' } unless @current_user
    else
      render json: { status: 'Unauthorized', code: 401, message: 'Unauthorized. Token invalid!' }
    end
  end
  
end

app/controllers/bikes_controller.rb
# frozen_string_literal: true

class BikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bike, only: %i[show edit update destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show; end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit; end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bike
    @bike = Bike.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bike_params
    params.require(:bike).permit(:vacancy_id, :with_problem)
  end
end

app/helpers/api/v1/bikes_helper.rb
# frozen_string_literal: true

module Api::V1::BikesHelper
end

app/helpers/bikes_helper.rb
# frozen_string_literal: true

module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
        <% bike.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vacancy_id %>
    <%= form.number_field :vacancy_id %>
  </div>

  <div class="field">
    <%= form.label :with_problem %>
    <%= form.check_box :with_problem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Vacancy</th>
      <th>With problem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.id %></td>
        <td><%= bike.vacancy_id %></td>
        <td><%= bike.with_problem %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vacancy:</strong>
  <%= @bike.vacancy_id %>
</p>

<p>
  <strong>With problem:</strong>
  <%= @bike.with_problem %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>